<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="workflow" nsURI="org.js.model.workflow" nsPrefix="workflow">
  <eClassifiers xsi:type="ecore:EClass" name="ACMConnector" eSuperTypes="platform:/plugin/org.eclipse.jwt.we.conf.model/model/ConfMetaModel.ecore#//AspectInstance">
    <eStructuralFeatures xsi:type="ecore:EReference" name="acmref" eType="ecore:EClass ../../../../org.js.model.rbac/src/main/model/rbac.ecore#//AccessControlModel"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RoleConnector" eSuperTypes="platform:/plugin/org.eclipse.jwt.we.conf.model/model/ConfMetaModel.ecore#//AspectInstance">
    <eStructuralFeatures xsi:type="ecore:EReference" name="roleref" eType="ecore:EClass ../../../../org.js.model.rbac/src/main/model/rbac.ecore#//Role"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EFMContainer" eSuperTypes="platform:/plugin/org.eclipse.jwt.we.conf.model/model/ConfMetaModel.ecore#//AspectInstance">
    <eStructuralFeatures xsi:type="ecore:EReference" name="efmref" eType="ecore:EClass ../../../../org.js.model.feature/src/main/model/feature.ecore#//FeatureModel"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Log" eSuperTypes="platform:/plugin/org.eclipse.jwt.we.conf.model/model/ConfMetaModel.ecore#//AspectInstance">
    <eStructuralFeatures xsi:type="ecore:EReference" name="configurationOperations"
        upperBound="-1" eType="ecore:EClass ../../../../org.js.model.rbac/src/main/model/rbac.ecore#//ConfigurationOperation"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="State" eSuperTypes="platform:/plugin/org.eclipse.jwt.we.conf.model/model/ConfMetaModel.ecore#//AspectInstance">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="state" eType="#//StateEnum"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="StateEnum">
    <eLiterals name="Inactive" literal="Inactive"/>
    <eLiterals name="Enabled" value="1" literal="Enabled"/>
    <eLiterals name="Running" value="2"/>
    <eLiterals name="Completed" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StakeholderTypes" eSuperTypes="platform:/plugin/org.eclipse.jwt.we.conf.model/model/ConfMetaModel.ecore#//AspectInstance">
    <eStructuralFeatures xsi:type="ecore:EReference" name="stakeholderTypes" upperBound="-1"
        eType="ecore:EClass ../../../../org.js.model.rbac/src/main/model/rbac.ecore#//Role"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GraphTransConnector" eSuperTypes="platform:/plugin/org.eclipse.jwt.we.conf.model/model/ConfMetaModel.ecore#//AspectInstance">
    <eStructuralFeatures xsi:type="ecore:EReference" name="graphTransref" eType="ecore:EClass ../../../../org.js.graph.transformation/src/main/model/graphTransformation.ecore#//GraphTransformation"/>
  </eClassifiers>
</ecore:EPackage>
