<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="expression" nsURI="http://www.tudresden.de/extexpression" nsPrefix="expression">
  <eClassifiers xsi:type="ecore:EClass" name="ExpressionModel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expressions" upperBound="-1"
        eType="ecore:EClass ../../../../org.js.model.feature/src/main/model/feature.ecore#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="calculations" upperBound="-1"
        eType="#//AttributeCalculation" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="comparisons" upperBound="-1"
        eType="#//AttributeComparison" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AttributeCalculation" eSuperTypes="../../../../org.js.model.feature/src/main/model/feature.ecore#//AtomicExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="attribute1calculation"
        lowerBound="1" eType="ecore:EClass ../../../../org.js.model.feature/src/main/model/feature.ecore#//AttributeOperand"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attribute2calculation"
        lowerBound="1" eType="ecore:EClass ../../../../org.js.model.feature/src/main/model/feature.ecore#//AttributeOperand"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operatorCalculation" lowerBound="1"
        eType="#//AttributeCalculationOperator"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="AttributeCalculationOperator">
    <eLiterals name="addition"/>
    <eLiterals name="subtraction" value="1"/>
    <eLiterals name="multiplication" value="2"/>
    <eLiterals name="division" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AttributeComparison" eSuperTypes="../../../../org.js.model.feature/src/main/model/feature.ecore#//AtomicExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="attribute1comparison" lowerBound="1"
        eType="ecore:EClass ../../../../org.js.model.feature/src/main/model/feature.ecore#//AttributeOperand"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attribute2comparison" lowerBound="1"
        eType="ecore:EClass ../../../../org.js.model.feature/src/main/model/feature.ecore#//AttributeOperand"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operatorComparison" lowerBound="1"
        eType="ecore:EEnum ../../../../org.js.model.feature/src/main/model/feature.ecore#//AttributeComparisonOperator"/>
  </eClassifiers>
</ecore:EPackage>
