<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="view" nsURI="http://www.conper.de/view" nsPrefix="view">
  <eClassifiers xsi:type="ecore:EClass" name="ViewContainer">
    <eStructuralFeatures xsi:type="ecore:EReference" name="views" upperBound="-1"
        eType="#//View" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="featureMapping" lowerBound="1"
        eType="ecore:EClass ../../../../org.feature.multi.perspective.mapping/src/main/model/viewmapping.ecore#//MappingModel"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="View">
    <eStructuralFeatures xsi:type="ecore:EReference" name="features" upperBound="-1"
        eType="ecore:EClass platform:/plugin/org.featuremapper.models.feature/model/feature.ecore#//Feature"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="viewgroups" upperBound="-1"
        eType="ecore:EClass ../../../../org.feature.multi.perspective.model/src/main/model/viewmodel.ecore#//AbstractGroup"/>
  </eClassifiers>
</ecore:EPackage>
