<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="feature" nsURI="http://www.tudresden.de/extfeature" nsPrefix="feature">
  <eClassifiers xsi:type="ecore:EClass" name="FeatureModel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="root" lowerBound="1" eType="#//Feature"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="domains" upperBound="-1"
        eType="#//Domain" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="constraints" upperBound="-1"
        eType="#//Constraint" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Feature" eSuperTypes="#//Identifiable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="configurationState" lowerBound="1"
        eType="#//FeatureState" defaultValueLiteral="unbound"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributes" upperBound="-1"
        eType="#//Attribute" containment="true" eOpposite="#//Attribute/feature"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="groups" upperBound="-1"
        eType="#//Group" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Group">
    <eStructuralFeatures xsi:type="ecore:EReference" name="childFeatures" lowerBound="1"
        upperBound="-1" eType="#//Feature" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="minCardinality" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxCardinality" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Attribute">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="feature" lowerBound="1"
        eType="#//Feature" eOpposite="#//Feature/attributes"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="domain" lowerBound="1"
        eType="#//Domain"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="deselectedDomainValues"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiscreteDomain" eSuperTypes="#//Domain">
    <eStructuralFeatures xsi:type="ecore:EReference" name="values" lowerBound="1"
        upperBound="-1" eType="#//DomainValue" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DomainValue">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="int" unique="false" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NumericalDomain" eSuperTypes="#//Domain">
    <eStructuralFeatures xsi:type="ecore:EReference" name="intervals" lowerBound="1"
        upperBound="-1" eType="#//Interval" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Domain" abstract="true" eSuperTypes="#//Identifiable"/>
  <eClassifiers xsi:type="ecore:EClass" name="Interval">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lowerBound" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="upperBound" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Identifiable" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Constraint" abstract="true"/>
  <eClassifiers xsi:type="ecore:EEnum" name="FeatureState">
    <eLiterals name="unbound"/>
    <eLiterals name="selected" value="1"/>
    <eLiterals name="deselected" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AttributeConstraint" eSuperTypes="#//Constraint">
    <eStructuralFeatures xsi:type="ecore:EReference" name="attribute1" lowerBound="1"
        eType="#//AttributeOperand" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attribute2" lowerBound="1"
        eType="#//AttributeOperand" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" lowerBound="1"
        eType="#//Relop"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Relop">
    <eLiterals name="equal"/>
    <eLiterals name="unequal" value="1"/>
    <eLiterals name="greaterThan" value="2"/>
    <eLiterals name="greaterThanOrEqual" value="3"/>
    <eLiterals name="lessThan" value="4"/>
    <eLiterals name="lessThanOrEqual" value="5"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AttributeOperand" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="AttributeReference" eSuperTypes="#//AttributeOperand">
    <eStructuralFeatures xsi:type="ecore:EReference" name="attribute" lowerBound="1"
        eType="#//Attribute"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="feature" lowerBound="1"
        eType="#//Feature"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AttributeValue" eSuperTypes="#//AttributeOperand">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="int" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FeatureConstraint" abstract="true" eSuperTypes="#//Constraint">
    <eStructuralFeatures xsi:type="ecore:EReference" name="leftOperand" lowerBound="1"
        eType="#//Feature"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rightOperand" lowerBound="1"
        eType="#//Feature"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Imply" eSuperTypes="#//FeatureConstraint"/>
  <eClassifiers xsi:type="ecore:EClass" name="Exclude" eSuperTypes="#//FeatureConstraint"/>
</ecore:EPackage>
